import fs from "fs";
import { type VocabularyItem, vocabularyData } from "./src/vocabularyData";

// Define the mapping
const categoryMapping: Record<string, VocabularyItem["category"]> = {
	// Time & Numbers
	tiempo: "Time & Numbers",
	año: "Time & Numbers",
	día: "Time & Numbers",
	hora: "Time & Numbers",
	mes: "Time & Numbers",
	semana: "Time & Numbers",
	noche: "Time & Numbers",
	tarde: "Time & Numbers",
	mañana: "Time & Numbers",
	hoy: "Time & Numbers",
	ayer: "Time & Numbers",
	ahora: "Time & Numbers",
	después: "Time & Numbers",
	antes: "Time & Numbers",
	siempre: "Time & Numbers",
	nunca: "Time & Numbers",
	mientras: "Time & Numbers",
	luego: "Time & Numbers",
	entonces: "Time & Numbers",
	vez: "Time & Numbers",
	momento: "Time & Numbers",
	principio: "Time & Numbers",
	fin: "Time & Numbers",
	siglo: "Time & Numbers",
	fecha: "Time & Numbers",
	edad: "Time & Numbers",
	época: "Time & Numbers",
	temporada: "Time & Numbers",
	estación: "Time & Numbers",
	primavera: "Time & Numbers",
	verano: "Time & Numbers",
	otoño: "Time & Numbers",
	invierno: "Time & Numbers",
	lunes: "Time & Numbers",
	martes: "Time & Numbers",
	miércoles: "Time & Numbers",
	jueves: "Time & Numbers",
	viernes: "Time & Numbers",
	sábado: "Time & Numbers",
	domingo: "Time & Numbers",
	enero: "Time & Numbers",
	febrero: "Time & Numbers",
	marzo: "Time & Numbers",
	abril: "Time & Numbers",
	mayo: "Time & Numbers",
	junio: "Time & Numbers",
	julio: "Time & Numbers",
	agosto: "Time & Numbers",
	septiembre: "Time & Numbers",
	octubre: "Time & Numbers",
	noviembre: "Time & Numbers",
	diciembre: "Time & Numbers",
	cero: "Time & Numbers",
	uno: "Time & Numbers",
	dos: "Time & Numbers",
	tres: "Time & Numbers",
	cuatro: "Time & Numbers",
	cinco: "Time & Numbers",
	seis: "Time & Numbers",
	siete: "Time & Numbers",
	ocho: "Time & Numbers",
	nueve: "Time & Numbers",
	diez: "Time & Numbers",
	once: "Time & Numbers",
	doce: "Time & Numbers",
	trece: "Time & Numbers",
	catorce: "Time & Numbers",
	quince: "Time & Numbers",
	veinte: "Time & Numbers",
	treinta: "Time & Numbers",
	cuarenta: "Time & Numbers",
	cincuenta: "Time & Numbers",
	sesenta: "Time & Numbers",
	setenta: "Time & Numbers",
	ochenta: "Time & Numbers",
	noventa: "Time & Numbers",
	cien: "Time & Numbers",
	mil: "Time & Numbers",
	millón: "Time & Numbers",
	primero: "Time & Numbers",
	segundo: "Time & Numbers",
	tercero: "Time & Numbers",
	último: "Time & Numbers",
	mitad: "Time & Numbers",
	cuarto: "Time & Numbers",
	par: "Time & Numbers",
	durante: "Time & Numbers",
	ya: "Time & Numbers",
	todavía: "Time & Numbers",
	aún: "Time & Numbers",
	jamás: "Time & Numbers",
	pronto: "Time & Numbers",
	temprano: "Time & Numbers",
	años: "Time & Numbers",
	meses: "Time & Numbers",
	días: "Time & Numbers",
	horas: "Time & Numbers",
	minutos: "Time & Numbers",
	segundos: "Time & Numbers",
	veces: "Time & Numbers",

	// People
	hombre: "People",
	mujer: "People",
	niño: "People",
	niña: "People",
	persona: "People",
	gente: "People",
	familia: "People",
	padre: "People",
	madre: "People",
	hijo: "People",
	hija: "People",
	hermano: "People",
	hermana: "People",
	abuelo: "People",
	abuela: "People",
	tío: "People",
	tía: "People",
	primo: "People",
	prima: "People",
	esposo: "People",
	esposa: "People",
	marido: "People",
	novio: "People",
	novia: "People",
	amigo: "People",
	amiga: "People",
	enemigo: "People",
	vecino: "People",
	compañero: "People",
	jefe: "People",
	empleado: "People",
	estudiante: "People",
	profesor: "People",
	maestro: "People",
	médico: "People",
	doctor: "People",
	paciente: "People",
	policía: "People",
	soldado: "People",
	rey: "People",
	reina: "People",
	presidente: "People",
	ministro: "People",
	ciudadano: "People",
	víctima: "People",
	autor: "People",
	actor: "People",
	cantante: "People",
	jugador: "People",
	equipo: "People",
	grupo: "People",
	comunidad: "People",
	población: "People",
	humano: "People",
	hombres: "People",
	mujeres: "People",
	niños: "People",
	niñas: "People",
	personas: "People",
	padres: "People",
	madres: "People",
	hijos: "People",
	hijas: "People",
	hermanos: "People",
	hermanas: "People",
	amigos: "People",
	amigas: "People",
	ella: "People",
	él: "People",
	yo: "People",
	tú: "People",
	nosotros: "People",
	nosotras: "People",
	vosotros: "People",
	vosotras: "People",
	ellos: "People",
	ellas: "People",
	usted: "People",
	ustedes: "People",
	mi: "People",
	tu: "People",
	su: "People",
	nuestro: "People",
	vuestro: "People",
	me: "People",
	te: "People",
	le: "People",
	nos: "People",
	os: "People",
	les: "People",
	quien: "People",
	quienes: "People",

	// Society
	gobierno: "Society",
	país: "Society",
	estado: "Society",
	nación: "Society",
	ciudad: "Society",
	pueblo: "Society",
	calle: "Society",
	camino: "Society",
	carretera: "Society",
	escuela: "Society",
	universidad: "Society",
	hospital: "Society",
	iglesia: "Society",
	banco: "Society",
	tienda: "Society",
	mercado: "Society",
	empresa: "Society",
	compañía: "Society",
	trabajo: "Society",
	empleo: "Society",
	dinero: "Society",
	precio: "Society",
	valor: "Society",
	costo: "Society",
	pago: "Society",
	venta: "Society",
	compra: "Society",
	ley: "Society",
	derecho: "Society",
	justicia: "Society",
	política: "Society",
	guerra: "Society",
	paz: "Society",
	seguridad: "Society",
	cultura: "Society",
	arte: "Society",
	historia: "Society",
	idioma: "Society",
	lenguaje: "Society",
	palabra: "Society",
	carta: "Society",
	mensaje: "Society",
	noticia: "Society",
	información: "Society",
	dato: "Society",
	programa: "Society",
	sistema: "Society",
	red: "Society",
	internet: "Society",
	teléfono: "Society",
	televisión: "Society",
	radio: "Society",
	diario: "Society",
	revista: "Society",
	libro: "Society",
	gobiernos: "Society",
	países: "Society",
	estados: "Society",
	naciones: "Society",
	ciudades: "Society",
	escuelas: "Society",
	universidades: "Society",
	hospitales: "Society",
	empresas: "Society",
	leyes: "Society",
	derechos: "Society",
	guerras: "Society",
	palabras: "Society",
	sistemas: "Society",
	redes: "Society",
	libros: "Society",
	social: "Society",
	público: "Society",
	nacional: "Society",
	internacional: "Society",
	económico: "Society",
	político: "Society",
	militar: "Society",
	legal: "Society",
	educativo: "Society",
	médico: "Society",
	religioso: "Society",

	// Verbs
	ser: "Verbs",
	estar: "Verbs",
	haber: "Verbs",
	tener: "Verbs",
	hacer: "Verbs",
	poder: "Verbs",
	decir: "Verbs",
	ir: "Verbs",
	ver: "Verbs",
	dar: "Verbs",
	saber: "Verbs",
	querer: "Verbs",
	llegar: "Verbs",
	pasar: "Verbs",
	deber: "Verbs",
	poner: "Verbs",
	parecer: "Verbs",
	quedar: "Verbs",
	creer: "Verbs",
	hablar: "Verbs",
	llevar: "Verbs",
	dejar: "Verbs",
	seguir: "Verbs",
	encontrar: "Verbs",
	llamar: "Verbs",
	venir: "Verbs",
	pensar: "Verbs",
	salir: "Verbs",
	volver: "Verbs",
	tomar: "Verbs",
	conocer: "Verbs",
	vivir: "Verbs",
	sentir: "Verbs",
	tratar: "Verbs",
	mirar: "Verbs",
	contar: "Verbs",
	empezar: "Verbs",
	esperar: "Verbs",
	buscar: "Verbs",
	existir: "Verbs",
	entrar: "Verbs",
	trabajar: "Verbs",
	escribir: "Verbs",
	perder: "Verbs",
	producir: "Verbs",
	ocurrir: "Verbs",
	entender: "Verbs",
	pedir: "Verbs",
	recibir: "Verbs",
	recordar: "Verbs",
	terminar: "Verbs",
	permitir: "Verbs",
	aparecer: "Verbs",
	conseguir: "Verbs",
	comenzar: "Verbs",
	servir: "Verbs",
	sacar: "Verbs",
	necesitar: "Verbs",
	mantener: "Verbs",
	resultar: "Verbs",
	leer: "Verbs",
	caer: "Verbs",
	cambiar: "Verbs",
	presentar: "Verbs",
	crear: "Verbs",
	abrir: "Verbs",
	considerar: "Verbs",
	oír: "Verbs",
	acabar: "Verbs",
	convertir: "Verbs",
	ganar: "Verbs",
	formar: "Verbs",
	traer: "Verbs",
	partir: "Verbs",
	morir: "Verbs",
	aceptar: "Verbs",
	realizar: "Verbs",
	suponer: "Verbs",
	comprender: "Verbs",
	lograr: "Verbs",
	explicar: "Verbs",
	preguntar: "Verbs",
	tocar: "Verbs",
	reconocer: "Verbs",
	estudiar: "Verbs",
	alcanzar: "Verbs",
	nacer: "Verbs",
	dirigir: "Verbs",
	correr: "Verbs",
	utilizar: "Verbs",
	pagar: "Verbs",
	ayudar: "Verbs",
	gustar: "Verbs",
	jugar: "Verbs",
	escuchar: "Verbs",
	cumplir: "Verbs",
	ofrecer: "Verbs",
	descubrir: "Verbs",
	levantar: "Verbs",
	intentar: "Verbs",
	es: "Verbs",
	son: "Verbs",
	fue: "Verbs",
	era: "Verbs",
	está: "Verbs",
	están: "Verbs",
	ha: "Verbs",
	han: "Verbs",
	había: "Verbs",
	hay: "Verbs",
	tiene: "Verbs",
	tienen: "Verbs",
	tenía: "Verbs",
	hace: "Verbs",
	hacen: "Verbs",
	hizo: "Verbs",
	puede: "Verbs",
	pueden: "Verbs",
	podía: "Verbs",
	dice: "Verbs",
	dicen: "Verbs",
	dijo: "Verbs",
	va: "Verbs",
	van: "Verbs",
	fue: "Verbs",
	ve: "Verbs",
	ven: "Verbs",
	vio: "Verbs",
	da: "Verbs",
	dan: "Verbs",
	dio: "Verbs",
	sabe: "Verbs",
	saben: "Verbs",
	quiere: "Verbs",
	quieren: "Verbs",
	llega: "Verbs",
	llegan: "Verbs",
	pasa: "Verbs",
	pasan: "Verbs",
	debe: "Verbs",
	deben: "Verbs",
	pone: "Verbs",
	ponen: "Verbs",
	parece: "Verbs",
	parecen: "Verbs",
	queda: "Verbs",
	quedan: "Verbs",
	cree: "Verbs",
	creen: "Verbs",
	habla: "Verbs",
	hablan: "Verbs",
	lleva: "Verbs",
	llevan: "Verbs",
	deja: "Verbs",
	dejan: "Verbs",
	sigue: "Verbs",
	siguen: "Verbs",
	encuentra: "Verbs",
	encuentran: "Verbs",
	llama: "Verbs",
	llaman: "Verbs",
	viene: "Verbs",
	vienen: "Verbs",
	piensa: "Verbs",
	piensan: "Verbs",
	sale: "Verbs",
	salen: "Verbs",
	vuelve: "Verbs",
	vuelven: "Verbs",
	toma: "Verbs",
	toman: "Verbs",
	conoce: "Verbs",
	conocen: "Verbs",
	vive: "Verbs",
	viven: "Verbs",
	siente: "Verbs",
	sienten: "Verbs",
	trata: "Verbs",
	tratan: "Verbs",
	mira: "Verbs",
	miran: "Verbs",
	cuenta: "Verbs",
	cuentan: "Verbs",
	empieza: "Verbs",
	empiezan: "Verbs",
	espera: "Verbs",
	esperan: "Verbs",
	busca: "Verbs",
	buscan: "Verbs",
	existe: "Verbs",
	existen: "Verbs",
	entra: "Verbs",
	entran: "Verbs",
	trabaja: "Verbs",
	trabajan: "Verbs",
	escribe: "Verbs",
	escriben: "Verbs",
	pierde: "Verbs",
	pierden: "Verbs",
	produce: "Verbs",
	producen: "Verbs",
	ocurre: "Verbs",
	ocurren: "Verbs",
	entiende: "Verbs",
	entienden: "Verbs",
	pide: "Verbs",
	piden: "Verbs",
	recibe: "Verbs",
	reciben: "Verbs",
	recuerda: "Verbs",
	recuerdan: "Verbs",
	termina: "Verbs",
	terminan: "Verbs",
	permite: "Verbs",
	permiten: "Verbs",
	aparece: "Verbs",
	aparecen: "Verbs",
	consigue: "Verbs",
	consiguen: "Verbs",
	comienza: "Verbs",
	comienzan: "Verbs",
	sirve: "Verbs",
	sirven: "Verbs",
	saca: "Verbs",
	sacan: "Verbs",
	necesita: "Verbs",
	necesitan: "Verbs",
	mantiene: "Verbs",
	mantienen: "Verbs",
	resulta: "Verbs",
	resultan: "Verbs",
	lee: "Verbs",
	leen: "Verbs",
	cae: "Verbs",
	caen: "Verbs",
	cambia: "Verbs",
	cambian: "Verbs",
	presenta: "Verbs",
	presentan: "Verbs",
	crea: "Verbs",
	crean: "Verbs",
	abre: "Verbs",
	abren: "Verbs",
	considera: "Verbs",
	consideran: "Verbs",
	oye: "Verbs",
	oyen: "Verbs",
	acaba: "Verbs",
	acaban: "Verbs",
	convierte: "Verbs",
	convierten: "Verbs",
	gana: "Verbs",
	ganan: "Verbs",
	forma: "Verbs",
	forman: "Verbs",
	trae: "Verbs",
	traen: "Verbs",
	parte: "Verbs",
	parten: "Verbs",
	muere: "Verbs",
	mueren: "Verbs",
	acepta: "Verbs",
	aceptan: "Verbs",
	realiza: "Verbs",
	realizan: "Verbs",
	supone: "Verbs",
	suponen: "Verbs",
	comprende: "Verbs",
	comprenden: "Verbs",
	logra: "Verbs",
	logran: "Verbs",
	explica: "Verbs",
	explican: "Verbs",
	pregunta: "Verbs",
	preguntan: "Verbs",
	toca: "Verbs",
	tocan: "Verbs",
	reconoce: "Verbs",
	reconocen: "Verbs",
	estudia: "Verbs",
	estudian: "Verbs",
	alcanza: "Verbs",
	alcanzan: "Verbs",
	nace: "Verbs",
	nacen: "Verbs",
	dirige: "Verbs",
	dirigen: "Verbs",
	corre: "Verbs",
	corren: "Verbs",
	utiliza: "Verbs",
	utilizan: "Verbs",
	paga: "Verbs",
	pagan: "Verbs",
	ayuda: "Verbs",
	ayudan: "Verbs",
	gusta: "Verbs",
	gustan: "Verbs",
	juega: "Verbs",
	juegan: "Verbs",
	escucha: "Verbs",
	escuchan: "Verbs",
	cumple: "Verbs",
	cumplen: "Verbs",
	ofrece: "Verbs",
	ofrecen: "Verbs",
	descubre: "Verbs",
	descubren: "Verbs",
	levanta: "Verbs",
	levantan: "Verbs",
	intenta: "Verbs",
	intentan: "Verbs",
	estaba: "Verbs",
	estaban: "Verbs",
	sido: "Verbs",
	dicho: "Verbs",
	hecho: "Verbs",
	visto: "Verbs",
	puesto: "Verbs",

	// Common Nouns
	agua: "Common Nouns",
	aire: "Common Nouns",
	fuego: "Common Nouns",
	tierra: "Common Nouns",
	sol: "Common Nouns",
	luna: "Common Nouns",
	estrella: "Common Nouns",
	cielo: "Common Nouns",
	mar: "Common Nouns",
	río: "Common Nouns",
	montaña: "Common Nouns",
	árbol: "Common Nouns",
	flor: "Common Nouns",
	bosque: "Common Nouns",
	piedra: "Common Nouns",
	animal: "Common Nouns",
	perro: "Common Nouns",
	gato: "Common Nouns",
	caballo: "Common Nouns",
	pájaro: "Common Nouns",
	pez: "Common Nouns",
	comida: "Common Nouns",
	pan: "Common Nouns",
	carne: "Common Nouns",
	fruta: "Common Nouns",
	manzana: "Common Nouns",
	mesa: "Common Nouns",
	silla: "Common Nouns",
	cama: "Common Nouns",
	puerta: "Common Nouns",
	ventana: "Common Nouns",
	casa: "Common Nouns",
	edificio: "Common Nouns",
	habitación: "Common Nouns",
	sala: "Common Nouns",
	cocina: "Common Nouns",
	baño: "Common Nouns",
	coche: "Common Nouns",
	auto: "Common Nouns",
	carro: "Common Nouns",
	autobús: "Common Nouns",
	tren: "Common Nouns",
	avión: "Common Nouns",
	barco: "Common Nouns",
	bicicleta: "Common Nouns",
	ropa: "Common Nouns",
	vestido: "Common Nouns",
	zapato: "Common Nouns",
	sombrero: "Common Nouns",
	mano: "Common Nouns",
	pie: "Common Nouns",
	cabeza: "Common Nouns",
	ojo: "Common Nouns",
	boca: "Common Nouns",
	nariz: "Common Nouns",
	oreja: "Common Nouns",
	pelo: "Common Nouns",
	cuerpo: "Common Nouns",
	sangre: "Common Nouns",
	corazón: "Common Nouns",
	luz: "Common Nouns",
	color: "Common Nouns",
	sonido: "Common Nouns",
	música: "Common Nouns",
	imagen: "Common Nouns",
	foto: "Common Nouns",
	papel: "Common Nouns",
	lápiz: "Common Nouns",
	bolígrafo: "Common Nouns",
	cosas: "Common Nouns",
	manos: "Common Nouns",
	ojos: "Common Nouns",
	zona: "Common Nouns",
	centro: "Common Nouns",
	lugar: "Common Nouns",
	fondo: "Common Nouns",
	lado: "Common Nouns",
	espacio: "Common Nouns",
	punto: "Common Nouns",
	línea: "Common Nouns",
	campo: "Common Nouns",
	suelo: "Common Nouns",
	camino: "Common Nouns",
	voz: "Common Nouns",
	paso: "Common Nouns",

	// Abstract
	vida: "Abstract",
	muerte: "Abstract",
	amor: "Abstract",
	odio: "Abstract",
	felicidad: "Abstract",
	tristeza: "Abstract",
	miedo: "Abstract",
	dolor: "Abstract",
	salud: "Abstract",
	enfermedad: "Abstract",
	fuerza: "Abstract",
	energía: "Abstract",
	poder: "Abstract",
	libertad: "Abstract",
	verdad: "Abstract",
	mentira: "Abstract",
	razón: "Abstract",
	causa: "Abstract",
	efecto: "Abstract",
	problema: "Abstract",
	solución: "Abstract",
	duda: "Abstract",
	pregunta: "Abstract",
	respuesta: "Abstract",
	idea: "Abstract",
	pensamiento: "Abstract",
	mente: "Abstract",
	alma: "Abstract",
	espíritu: "Abstract",
	dios: "Abstract",
	religión: "Abstract",
	fe: "Abstract",
	esperanza: "Abstract",
	suerte: "Abstract",
	destino: "Abstract",
	naturaleza: "Abstract",
	mundo: "Abstract",
	universo: "Abstract",
	forma: "Abstract",
	tamaño: "Abstract",
	peso: "Abstract",
	velocidad: "Abstract",
	modo: "Abstract",
	manera: "Abstract",
	estilo: "Abstract",
	tipo: "Abstract",
	clase: "Abstract",
	orden: "Abstract",
	nivel: "Abstract",
	grado: "Abstract",
	calidad: "Abstract",
	cantidad: "Abstract",
	parte: "Abstract",
	todo: "Abstract",
	nada: "Abstract",
	algo: "Abstract",
	cosa: "Abstract",
	objeto: "Abstract",
	tema: "Abstract",
	asunto: "Abstract",
	caso: "Abstract",
	ejemplo: "Abstract",
	hecho: "Abstract",
	realidad: "Abstract",
	sueño: "Abstract",
	nombre: "Abstract",
	sentido: "Abstract",
	cambio: "Abstract",
	situación: "Abstract",
	interés: "Abstract",
	acuerdo: "Abstract",
	movimiento: "Abstract",
	acción: "Abstract",
	resultado: "Abstract",
	servicio: "Abstract",
	actividad: "Abstract",
	atención: "Abstract",
	experiencia: "Abstract",
	posibilidad: "Abstract",
	condición: "Abstract",
	efecto: "Abstract",
	carácter: "Abstract",
	vista: "Abstract",
	presencia: "Abstract",
	falta: "Abstract",
	necesidad: "Abstract",
	importancia: "Abstract",

	// Adjectives
	grande: "Adjectives",
	pequeño: "Adjectives",
	bueno: "Adjectives",
	malo: "Adjectives",
	bonito: "Adjectives",
	feo: "Adjectives",
	joven: "Adjectives",
	viejo: "Adjectives",
	caliente: "Adjectives",
	frío: "Adjectives",
	feliz: "Adjectives",
	triste: "Adjectives",
	fuerte: "Adjectives",
	débil: "Adjectives",
	rico: "Adjectives",
	pobre: "Adjectives",
	alto: "Adjectives",
	bajo: "Adjectives",
	gordo: "Adjectives",
	delgado: "Adjectives",
	rápido: "Adjectives",
	lento: "Adjectives",
	inteligente: "Adjectives",
	tonto: "Adjectives",
	interesante: "Adjectives",
	aburrido: "Adjectives",
	famoso: "Adjectives",
	desconocido: "Adjectives",
	nuevo: "Adjectives",
	antiguo: "Adjectives",
	moderno: "Adjectives",
	tradicional: "Adjectives",
	caro: "Adjectives",
	barato: "Adjectives",
	difícil: "Adjectives",
	peligroso: "Adjectives",
	seguro: "Adjectives",
	cómodo: "Adjectives",
	incómodo: "Adjectives",
	limpio: "Adjectives",
	sucio: "Adjectives",
	lleno: "Adjectives",
	vacío: "Adjectives",
	abierto: "Adjectives",
	cerrado: "Adjectives",
	claro: "Adjectives",
	oscuro: "Adjectives",
	duro: "Adjectives",
	blando: "Adjectives",
	dulce: "Adjectives",
	salado: "Adjectives",
	amargo: "Adjectives",
	ácido: "Adjectives",
	calmado: "Adjectives",
	nervioso: "Adjectives",
	amable: "Adjectives",
	simpático: "Adjectives",
	antipático: "Adjectives",
	alegre: "Adjectives",
	serio: "Adjectives",
	divertido: "Adjectives",
	tímido: "Adjectives",
	extrovertido: "Adjectives",
	introvertido: "Adjectives",
	trabajador: "Adjectives",
	perezoso: "Adjectives",
	generoso: "Adjectives",
	egoísta: "Adjectives",
	honesto: "Adjectives",
	mentiroso: "Adjectives",
	paciente: "Adjectives",
	impaciente: "Adjectives",
	valiente: "Adjectives",
	cobarde: "Adjectives",
	optimista: "Adjectives",
	pesimista: "Adjectives",
	responsable: "Adjectives",
	irresponsable: "Adjectives",
	educado: "Adjectives",
	maleducado: "Adjectives",
	agradable: "Adjectives",
	desagradable: "Adjectives",
	saludable: "Adjectives",
	enfermo: "Adjectives",
	cansado: "Adjectives",
	energético: "Adjectives",
	ocupado: "Adjectives",
	libre: "Adjectives",
	casado: "Adjectives",
	soltero: "Adjectives",
	divorciado: "Adjectives",
	viudo: "Adjectives",
	embarazada: "Adjectives",
	orgulloso: "Adjectives",
	celoso: "Adjectives",
	sorprendido: "Adjectives",
	asustado: "Adjectives",
	preocupado: "Adjectives",
	confundido: "Adjectives",
	grandes: "Adjectives",
	pequeños: "Adjectives",
	buenos: "Adjectives",
	malos: "Adjectives",
	nuevos: "Adjectives",
	viejos: "Adjectives",
	importantes: "Adjectives",
	sociales: "Adjectives",
	políticos: "Adjectives",
	económicos: "Adjectives",
	humanos: "Adjectives",
	generales: "Adjectives",
	posible: "Adjectives",
	imposible: "Adjectives",
	real: "Adjectives",
	personal: "Adjectives",
	único: "Adjectives",
	necesario: "Adjectives",
	difícil: "Adjectives",
	fácil: "Adjectives",
	igual: "Adjectives",
	distinto: "Adjectives",
	mayor: "Adjectives",
	menor: "Adjectives",
	mejor: "Adjectives",
	peor: "Adjectives",
	propio: "Adjectives",
	ajeno: "Adjectives",
	cierto: "Adjectives",
	falso: "Adjectives",
	seguro: "Adjectives",
	libre: "Adjectives",
	público: "Adjectives",
	privado: "Adjectives",
	común: "Adjectives",
	especial: "Adjectives",
	simple: "Adjectives",
	complejo: "Adjectives",
	blanco: "Adjectives",
	negro: "Adjectives",
	rojo: "Adjectives",
	azul: "Adjectives",
	verde: "Adjectives",
	amarillo: "Adjectives",
	gris: "Adjectives",

	// Grammar (Default fallback for small words)
	de: "Grammar",
	la: "Grammar",
	que: "Grammar",
	el: "Grammar",
	en: "Grammar",
	y: "Grammar",
	a: "Grammar",
	los: "Grammar",
	se: "Grammar",
	del: "Grammar",
	las: "Grammar",
	un: "Grammar",
	por: "Grammar",
	con: "Grammar",
	no: "Grammar",
	una: "Grammar",
	para: "Grammar",
	al: "Grammar",
	lo: "Grammar",
	como: "Grammar",
	más: "Grammar",
	o: "Grammar",
	pero: "Grammar",
	sus: "Grammar",
	si: "Grammar",
	sin: "Grammar",
	sobre: "Grammar",
	este: "Grammar",
	entre: "Grammar",
	todo: "Grammar",
	esta: "Grammar",
	muy: "Grammar",
	hasta: "Grammar",
	desde: "Grammar",
	porque: "Grammar",
	qué: "Grammar",
	sólo: "Grammar",
	todos: "Grammar",
	así: "Grammar",
	ni: "Grammar",
	donde: "Grammar",
	bien: "Grammar",
	mismo: "Grammar",
	ese: "Grammar",
	cada: "Grammar",
	e: "Grammar",
	otro: "Grammar",
	otros: "Grammar",
	aunque: "Grammar",
	esa: "Grammar",
	eso: "Grammar",
	otra: "Grammar",
	tan: "Grammar",
	tanto: "Grammar",
	según: "Grammar",
	menos: "Grammar",
	contra: "Grammar",
	sino: "Grammar",
	poco: "Grammar",
	estos: "Grammar",
	ante: "Grammar",
	unos: "Grammar",
	hacia: "Grammar",
	ello: "Grammar",
	pues: "Grammar",
	tras: "Grammar",
	además: "Grammar",
	embargo: "Grammar",
	pesar: "Grammar",
	dentro: "Grammar",
	bajo: "Grammar",
	frente: "Grammar",
	junto: "Grammar",
	medio: "Grammar",
	través: "Grammar",
	cual: "Grammar",
  casi: 'Grammar',
};

let updatedCount = 0;
const unknownWords: string[] = [];

const updatedData = vocabularyData.map((item) => {
  if (item.category === "General") {
		const lowerWord = item.word.toLowerCase();
		const newCategory = categoryMapping[lowerWord];
		if (newCategory) {
			updatedCount++;
			return { ...item, category: newCategory };
		} else {
			unknownWords.push(item.word);
			// Fallback strategies based on endings or patterns could go here,
			// but for now we keep it as General or default to Grammar/Abstract if we want to force it.
			// Let's default to 'Abstract' for unknown words to clear 'General' completely if possible,
			// or just log them.
			// For safety, let's keep 'General' if not found, but we want to eliminate it.
			// Let's try to guess:
			if (
				lowerWord.endsWith("ar") ||
				lowerWord.endsWith("er") ||
				lowerWord.endsWith("ir")
			) {
				// Likely a verb
				return { ...item, category: "Verbs" };
			}
			return item;
		}
	}
	return item;
});

console.log(`Updated ${updatedCount} items.`);
console.log("Unknown words:", JSON.stringify(unknownWords, null, 2));

const content = `export interface VocabularyItem {
  id: string;
  word: string;
  translation: string;
  level: 'Basic' | 'Intermediate' | 'Advanced';
  category: 'Greetings' | 'Food' | 'Travel' | 'Family' | 'Nature' | 'General' | 'Grammar' | 'Verbs' | 'Common Nouns' | 'Time & Numbers' | 'People' | 'Society' | 'Abstract' | 'Adjectives';
  image: string;
  ipa: string;
  example: string;
  exampleTranslation: string;
  gender?: 'Masculine' | 'Feminine';
}

export const vocabularyData: VocabularyItem[] = ${JSON.stringify(updatedData, null, 2)};
`;

fs.writeFileSync("./src/vocabularyData.ts", content);
